---
title: "Glove Study"
author: "Netasha"
date: "2024-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  An experiment was conducted to investigate the effect of an educational program on compliance with glove use in a cardiology department of a hospital. The participants in the study were all 23 members of the department’s nursing staff. They all attended an educational program addressing the importance of wearing gloves. Without their knowledge, the nurses were observed during heart valve surgeries before and one, two, and five months after an educational program to see how often they wore gloves. Each procedure by a nurse was counted as a separate observation. The dataset glove.dat contains the following variables:

    -   Period Observation period (1 = before intervention, 2 = one month after intervention, 3 = two months after, 4 = 5 months after intervention)

    -   Observed Number of times the nurse was observed

    -   Gloves Number of times the nurse used gloves

    -   Experience Years of experience of nurse

        					

        				

        			

        		

        	
        					

        				

        			

        		

        	
